server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mybatis?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: 12345678
    driver-class-name: com.mysql.jdbc.Driver

########## Mybatis 自身配置 ##########
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: marco.springboot.mybatisdemo.entity
